[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
  force = false
  conditions = {Language = ["ja"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = false